<?php
/**
 * Created by.
 * User: Jim
 * Date: 2020/7/17
 * Time: 9:49
 */

namespace app\common\controller;


use think\Controller;

/**
 * 后台基础类
 * Class Backend
 * @package app\common\controller
 */
class Backend extends Controller
{

    use \app\admin\libs\traits\Backend;


    /**
     * 无需登录的方法,同时也就不需要鉴权了
     * @var array
     */
    protected $noNeedLogin = [];

    /**
     * 无需鉴权的方法,但需要登录
     * @var array
     */
    protected $noNeedRight = [];


    /**
     * Model对象
     * @var null
     */
    protected $model = null;

    /**
     * 验证器对象
     * @var null
     */
    protected $_validate = null;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        /**
         * 需要集成auth权限 等待完善
         */
        $this->auth();

    }

    /**
     * 等待重写
     * 用户授权认证
     * @return bool
     */
    public function auth(){
        $action = strtolower($this->request->action());

//        不需要授权
        if (in_array('*',$this->noNeedLogin)) return true;
        if (in_array($action,$this->noNeedLogin)) return true;

        //验证权限是否通过
//        ...

        /**
         * 1，这里验证是否可以登录
         * 2，admin控制器中验证是否存在权限
         */
        return true;
    }




}