<?php
/**
 * Created by.
 * User: Jim
 * Date: 2020/7/17
 * Time: 10:20
 */

namespace app\admin\controller\auth;


use app\common\controller\Backend;

/**
 * 后台管理员Auth 权限认证
 * Class Admin
 * @package app\admin\controller\auth
 */
class Admin extends Backend
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\auth\Admin();
        $this->_validate= new \app\admin\validate\auth\Admin();

    }

}