<?php
/**
 * Created by.
 * User: Jim
 * Date: 2020/7/24
 * Time: 17:13
 */

namespace app\api\libs\auth;


use app\api\libs\traits\Api;
use think\Controller;

/**
 * api 授权
 * Class Auth
 * @package app\api\libs\auth
 */
class Auth extends Controller
{
    use Api;


    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub



    }


}