<?php
/**
 * Created by.
 * User: Jim
 * Date: 2020/7/24
 * Time: 17:13
 */

namespace app\api\libs\auth;


use app\api\libs\traits\Api;
use think\Controller;

/**
 * api 授权 这里写授权认证
 * Class Auth
 * @package app\api\libs\auth
 */
class Auth extends \app\common\controller\Api
{


    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->checkAuth();

    }


    protected function checkAuth(){
        $action = strtolower($this->request->action());
        $headers = $this->request->header();

        if (in_array($action,$this->noNeedLogin)){
            // 不需要登录授权
            return true;
        }

        /**
         * 检测授权码是否通过
         */

        // coding....
        return true;

    }

}