<?php
/**
 * Created by.
 * User: Jim
 * Date: 2020/7/24
 * Time: 17:13
 */

namespace app\api\libs\auth;


use app\common\controller\Api;
use app\common\libs\exception\ApiException;
use think\Controller;

/**
 * api 授权 这里写授权认证
 * Class Auth
 * @package app\api\libs\auth
 */
class Auth extends Controller
{
    /**
     * 无需登录的方法,同时也就不需要鉴权了
     * @var array
     */
    public $noNeedLogin = [];


    /**
     * 权限控制类
     * @var Auth
     */
    public $auth = null;

    /**
     * 模型对象
     * @var \think\Model
     */
    public $model = null;

    /**
     * Validate验证
     */
    public $_validate = false;

    /**
     * 数据获取最大的数量
     */
    public $dataLimitCount = 100;



    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->checkAuth();

    }


    protected function checkAuth(){
        $action = strtolower($this->request->action());
        $headers = $this->request->header();

        if (in_array($action,$this->noNeedLogin)){
            // 不需要登录授权
            return true;
        }

        if (!isset($headers['authorization']) || $headers['authorization'] == ''){
            throw new ApiException('授权码不正确');
        }

        /**
         * 检测授权码是否通过
         * coding....
         */
        $userInfo = Jwt::checkToken($headers['authorization']);

        return $userInfo;

    }


}